apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-ai-path
spec:
  rules:
  - host: local-ai-path.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: local-ai-path
            port:
              number: 80